name: Deploy Bot on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm ~/.pm2/logs/zbot-error.log
            rm ~/.pm2/logs/zbot-out.log
            cd ~/BOT/Z-BOT
            git pull origin main
            npm install
            pm2 restart zbot
